openapi: 3.0.1
info:
  title: Revolution Parts APIs
  version: "4.0"
  x-logo:
    url: https://s3.amazonaws.com/static.revolutionparts.com/assets/logos/rp-logo-stroke.png
servers:
- url: //api.revolutionparts.com/
tags:
- name: Vehicle

paths:
  /vehicle/{id}:
    get:
      tags:
        - Vehicle
      summary: Get vehcle by internal RP vehicle id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'
  /vehicle/finder/vin:
    get:
      tags:
        - Vehicle
      summary: Lookup vehicle by vin
      parameters:
        - name: vin
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vehicle'

components:
  schemas:
    Vehicle:
      type: object
      properties:
        id:
          type: integer
          description: Internal RP Vehicle ID.
          example: 1234
        year:
          type: integer
          description: The 4 digit year.
          example: 2021
        make:
          type: string
          description: The vehcle make.
          example: Ford
        model:
          type: string
          description: The vehicle model
          example: F150
